top_modules:
    - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*/fastqc/*_fastqc.zip'
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        target: ''
        path_filters:
            - '*/trim_galore/*_fastqc.zip'
    - cutadapt
    - samtools:
        name: 'Samtools (pre-filtering)'
        path_filters:
            - '*/bowtie2/*'
    - samtools:
        name: 'Samtools (post-filtering)'
        info: 'Samtools after filtering'
        target: ''
        path_filters:
            - '*/bowtie2_filt/*'
    - picard:
        name: 'Picard (pre-filtering)'
        info: 'Picard metrics; Recall that Picard removes duplicates by default for insert size distribution.'
        path_filters:
            - '*/bowtie2/*'
    - picard:
        name: 'Picard (post-filtering)'
        info: 'Picard metrics after filtering'
        target: ''
        path_filters:
            - '*/bowtie2_filt/*'
    - qualimap:
        name: 'Qualimap (pre-filtering)'
        path_filters:
            - '*/bowtie2/*'
    - qualimap:
        name: 'Qualimap (post-filtering)'
        info: 'Qualimap after filtering'
        target: ''
        path_filters:
            - '*/bowtie2_filt/*'

extra_fn_clean_trim:
     - "_val_1"
     - "_val_2"

# Other MultiQC config stuff here
custom_data:
  all_frip:
    parent_id: "FRiP"
    parent_name: "FRiP"
    parent_description: "This section contains subsections for FRiP based on:\n1. Peaks merged across all samples.\n2. Peaks merged over the samples within each respective experimental group.\nChoose which peak type (e.g. MACS3 narrow vs broad) to use in the config file."
    file_format: "csv"
    section_name: "All FRiP"
    description: "Calculate FRiP scores using peaks merged across all samples. Set peak type in config file."
    plot_type: "bargraph"
    pconfig:
      id: "FRiP_barplot"
      title: "FRiP"
      ylab: "FRiP"
      cpswitch_c_active: False
  group_frip:
    parent_id: "FRiP"
    file_format: "csv"
    section_name: "Group FRiP"
    description: "Calculate FRiP scores using peaks merged across experimental group. Set peak type in config file."
    plot_type: "bargraph"
    pconfig:
      id: "FRiP_barplot"
      title: "FRiP"
      ylab: "FRiP"
      cpswitch_c_active: False
sp:
  all_frip:
    fn: "all_frip.csv"
  group_frip:
    fn: "group_frip.csv"

