# Other MultiQC config stuff here
custom_data:
  all_frip:
    parent_id: "FRiP"
    parent_name: "FRiP"
    parent_description: "This section contains subsections for FRiP based on:\n1. Peaks merged across all samples.\n2. Peaks merged over the samples within each respective experimental group.\nChoose which peak type (e.g. MACS3 narrow vs broad) to use in the config file."
    file_format: "csv"
    section_name: "All FRiP"
    description: "Calculate FRiP scores using peaks merged across all samples. Set peak type in config file."
    plot_type: "bargraph"
    pconfig:
      id: "FRiP_barplot"
      title: "FRiP"
      ylab: "FRiP"
      cpswitch_c_active: False
  group_frip:
    parent_id: "FRiP"
    file_format: "csv"
    section_name: "Group FRiP"
    description: "Calculate FRiP scores using peaks merged across experimental group. Set peak type in config file."
    plot_type: "bargraph"
    pconfig:
      id: "FRiP_barplot"
      title: "FRiP"
      ylab: "FRiP"
      cpswitch_c_active: False
sp:
  all_frip:
    fn: "all_frip.csv"
  group_frip:
    fn: "group_frip.csv"

